version: '3'

services:
  web1:
    build: ./web1
    ports:
      - "8081:8080"

  web2:
    build: ./web2
    ports:
      - "8082:8080"

  nginx-round-robin:
    build: ./nginx-round-robin
    ports:
      - "8001:80"
    depends_on:
      - web1
      - web2

  nginx-ip-hash:
    build: ./nginx-ip-hash
    ports:
      - "8002:80"
    depends_on:
      - web1
      - web2
